### ISSUE TITLE
Missing Navigation Bar

### ISSUE THREAD

**Issue by Smithy31** [ricoshae/ricoshaejs#1]
Hi have installed the "ricoshajs" plugin into Moodle the installation ran with no apparent issues but the black navigation bar with the arrows are not visible not quite sure what is causing the bar not to show any help would be greatly appreciated.

**Comment by christophermrichter** [comment]
Hi Smithy31, The black navigation bar is part of the Moodle theme that was used to demonstrate the plugin, it isn't actually part of the plugin. The navigation was created with this plugin https://moodle.org/plugins/block_navbuttons but with the icons changed to FontAwesome arrow. The latest release of Moodle has the arrows as part of core so you don't need the navbuttons plugin to have the arrows to move between content pages.  Hope this helps.
